[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0016"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0003"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[general]
live_config_reload = true
import = ["~/.config/alacritty/current-theme.toml"]

[scrolling]
history = 10000

[window]
decorations = "none"
opacity = 0.9
padding = { x = 8, y = 8 }

